version: '2'

services:
    nginx:
        restart: always
        image: nginx:latest
        volumes:
            - ../var/etc/ssl:/etc/ssl
            - ../var/etc/nginx/nginx.conf:/etc/nginx/nginx.conf
            - ../var/log/nginx:/var/log/nginx
        container_name: {{ project_name }}_nginx

    {{ project_name }}_app:
        restart: always
        build:
            context: ../
        image: {{ project_name }}_app:latest
        env_file:
            - ../var/etc/app.env
            - ../var/etc/rabbitmq.env
            - ../var/etc/pgsql.env
        volumes:
            - ../:/home/caffeine/project
        user: "1000:caffeine"
        container_name: {{ project_name }}_app
        working_dir: "/home/caffeine/project"
        command: ["/home/caffeine/project/var/bin/docker-start.sh"]

    postgres:
        restart: always
        image: postgres:latest
        env_file:
            - ../var/etc/pgsql.env
        volumes:
            - ../var/etc/postgres/initdb.d/init-db-user.sh:/docker-entrypoint-initdb.d/init-db-user.sh
            - ../var/lib/postgres:/var/lib/postgresql/data/
        container_name: {{ project_name }}_pgsql

    rabbitmq:
        restart: always
        image: rabbitmq:management
        env_file:
            - ../var/etc/rabbitmq.env
        volumes:
            - ../var/lib/rabbitmq:/var/lib/rabbitmq/mnesia/rabbit@caffeine_rq
        hostname: "caffeine_rq"
        container_name: {{ project_name }}_rabbitmq

    memcached:
        restart: always
        image: memcached:latest
        container_name: {{ project_name }}_memcached

    redis:
        restart: always
        image: redis:latest
        volumes:
            - ../var/lib/redis:/data
        container_name: {{ project_name }}_redis

