version: '2'

services:
    postgres:
        restart: always
        image: postgres:9.5
        volumes:
            - ../scripts/init-db-user.sh:/docker-entrypoint-initdb.d/init-db-user.sh
            - ../var/db/postgres:/var/lib/postgresql/data/
        ports:
            - "8013:5432"
        env_file:
            - ../.env
        container_name: app_db

    redis:
        restart: always
        build:
            context: ../
            dockerfile: DockerfileRedis
        image: sentinel_redis
        volumes:
            - ../var/db/redis:/data
        container_name: app_rd

    rabbitmq:
        restart: always
        image: rabbitmq:latest
        volumes:
            - ../var/db/rabbitmq:/var/lib/rabbitmq/mnesia/rabbit@app_rq
        ports:
            - "8014:15672"
        hostname: "app_rq"
        env_file:
            - ../.env
        container_name: app_rq

    web:
        restart: always
        build:
            context: ../
        image: app_web
        volumes:
            - ../:/srv/caffeine/project
        env_file:
            - ../.env
        container_name: app_web
        ports:
            - "8015:8000"
            - "2767:22"
        working_dir: "/srv/caffeine/project"
        command: scripts/docker_start.sh
