version: '2'

services:
    postgres:
        restart: always
        image: postgres:9.5
        volumes:
            - ../scripts/init-db-user.sh:/docker-entrypoint-initdb.d/init-db-user.sh
            - ../db/postgres:/var/lib/postgresql/data/
        ports:
            - "8013:5432"
        env_file:
            - ../scripts/vars.env
        container_name: can_db

    redis:
        restart: always
        image: redis:latest
        volumes:
            - ../db/redis:/data
        container_name: can_rd

    rabbitmq:
        restart: always
        image: rabbitmq:latest
        volumes:
            - ../db/rabbitmq:/var/lib/rabbitmq/mnesia/rabbit@can_rq
        ports:
            - "8014:15672"
        hostname: "can_rq"
        env_file:
            - ../scripts/vars.env
        container_name: can_rq

    web:
        restart: always
        build:
            context: ../
        image: can_web
        volumes:
            - ../:/srv/caffeine/abm
        env_file:
            - ../scripts/vars.env
        container_name: can_web
        ports:
            - "8015:8000"
            - "2767:22"
        working_dir: "/srv/caffeine/abm"
        command: scripts/docker_start.sh
