version: '2'

services:
    nginx:
        extends:
            file: base.yml
            service: nginx
        ports:
            - "8020:80"
            - "8022:443"
        volumes:
            - ../var/etc/nginx/sites-enabled.dev:/etc/nginx/sites-enabled
        volumes_from:
            - {{ project_name }}_app
        links:
            - postgres
            - rabbitmq
            - memcached
            - redis
            - {{ project_name }}_app

    {{ project_name }}_app:
        extends:
            file: base.yml
            service: {{ project_name }}_app
        command: ["/home/caffeine/project/var/bin/gunicorn-start.sh"]

    postgres:
        extends:
            file: base.yml
            service: postgres

    rabbitmq:
        extends:
            file: base.yml
            service: rabbitmq

    memcached:
        extends:
            file: base.yml
            service: memcached

    redis:
        extends:
            file: base.yml
            service: redis
