version: '2'

services:
    nginx:
        extends:
            file: base.yml
            service: nginx
        ports:
            - "80:80"
            - "443:443"
        volumes_from:
            - {{ project_name }}_app
        links:
            - postgres
            - rabbitmq
            - memcached
            - redis
            - {{ project_name }}_app

    {{ project_name }}_app:
        extends:
            file: base.yml
            service: {{ project_name }}_app

    postgres:
        ports:
            - "2345:5432"
        extends:
            file: base.yml
            service: postgres

    rabbitmq:
        extends:
            file: base.yml
            service: rabbitmq

    memcached:
        extends:
            file: base.yml
            service: memcached

    redis:
        extends:
            file: base.yml
            service: redis
